workflows:
  android-build:
    name: Android APK Build
    scripts:
      # make sure the wrapper is runnable, then build
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      # grab your debug APK
      - app/build/outputs/apk/debug/*.apk
