workflows:
  android-build:
    name: Android APK Build
    scripts:
      # move into the android folder, make the wrapper executable, then build
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      # where to find your debug APK
      - android/app/build/outputs/apk/debug/*.apk
